services/web/app/routes.py
import os

from flask import (
    flash,
    redirect,
    render_template,
    request,
    url_for,
    Blueprint,
)
import tekore as tk
from flask_login import (
    current_user,
    login_required,
    login_user,
    logout_user,
    LoginManager,
)
from werkzeug.urls import url_parse

from app.forms import LoginForm, RegistrationForm, PlaylistInputForm, PlaylistSearchForm
from app.models import User, Track, Playlist
from extensions import db

import tasks


route_blueprint = Blueprint("route_blueprint", __name__)

conf = (
    os.getenv("SPOTIFY_CLIENT_ID"),
    os.getenv("SPOTIFY_CLIENT_SECRET"),
    os.getenv("SPOTIFY_CALLBACK_URL"),
)
cred = tk.Credentials(*conf)
spotify = tk.Spotify()

login_manager = LoginManager()
login_manager.login_view = "login"


@login_manager.user_loader
def load_user(id):
    return User.query.get(int(id))


auths = {}


@route_blueprint.route("/")
@route_blueprint.route("/index")
def index():
    playlist_count = Playlist.query.count()
    track_count = Track.query.count()
    return render_template(
        "index.html",
        title="Home",
        playlist_count=playlist_count,
        track_count=track_count,
    )


@route_blueprint.route("/playlists", methods=["GET"])
def playlists():
    return render_template(
        "search_playlists.html",
        title="Search Playlists",
        form=PlaylistSearchForm(),
        results="",
    )


@route_blueprint.route("/playlists", methods=["POST"])
def search_playlists():
    form = PlaylistSearchForm()
    if form.validate_on_submit():
        if link := form.track_link.data:
            track_id = link.split("/")[-1].split("?")[0]
            track = Track.query.filter_by(spotify_id=track_id).first()
        else:
            track = Track.query.filter_by(name=form.track_name.data).first()

        if track:
            # default
            results = "Track found, but no new playlists contain it"

            # Find playlists that contain the track
            results = track.get_playlists()
            results = [p for p in results]

        else:
            results = "Track not found, try again!"

        return render_template(
            "search_playlists.html",
            title="Search Playlists",
            form=form,
            results=results,
        )


@route_blueprint.route("/playlists/import", methods=["GET", "POST"])
def import_playlists():
    form = PlaylistInputForm()
    if form.validate_on_submit():
        playlist_ids = form.playlist_ids.data.split(",")
        # if very many playlists, chunk into 100s
        if len(playlist_ids) > 500:
            chunk_size = 100
            for pos in range(0, len(playlist_ids), chunk_size):
                chunk = playlist_ids[pos: (pos + chunk_size)]
                tasks.process_data.delay(chunk)
        else:
            tasks.process_data.delay(playlist_ids)

    return render_template("import_playlists.html", title="Import Playlists", form=form)


@route_blueprint.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("route_blueprint.index"))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is None or not user.check_password(form.password.data):
            flash("Invalid username or password")
            return redirect(url_for("route_blueprint.login"))
        login_user(user, remember=form.remember_me.data)
        next_page = request.args.get("next")
        if not next_page or url_parse(next_page).netloc != "":
            next_page = url_for("route_blueprint.search_playlists")
        return redirect(next_page)
    return render_template("login.html", title="Sign In", form=form)


@route_blueprint.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("route_blueprint.index"))


@route_blueprint.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("route_blueprint.index"))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(username=form.username.data, email=form.email.data)
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for("route_blueprint.login"))
    return render_template("register.html", title="Register", form=form)

services/web/app/templates/base.html
<html>

<head>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% if title %}
    <title>{{ title }} - Spotify Playlist Lookup</title>
    {% else %}
    <title>Welcome to Spotify Playlist Lookup!</title>
    {% endif %}

    {% if config['ENV'] == 'production' %}
    <!-- Matomo -->
    <script>
        var _paq = window._paq = window._paq || [];
        /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
        _paq.push(['trackPageView']);
        _paq.push(['enableLinkTracking']);
        (function () {
            var u = "//matomo.dags.dev/";
            _paq.push(['setTrackerUrl', u + 'matomo.php']);
            _paq.push(['setSiteId', '1']);
            var d = document, g = d.createElement('script'), s = d.getElementsByTagName('script')[0];
            g.async = true; g.src = u + 'matomo.js'; s.parentNode.insertBefore(g, s);
        })();
    </script>
    <!-- End Matomo Code -->
    {% endif %}
</head>

<body>
    <div id="navbar">
        <div id="left-links">
            <a href="{{ url_for('route_blueprint.index') }}">Home</a>
            <a href="{{ url_for('route_blueprint.search_playlists') }}">Search Playlists</a>
            <a href="{{ url_for('route_blueprint.import_playlists') }}">Import Playlists</a>
        </div>
        <a id="repo-link" href="https://github.com/NomadicDaggy/spotify-playlist-lookup">
            <img id="gh-logo" src="{{ url_for('static', filename='img/GitHub-Mark-Light-32px.png') }}"
                alt="Github Logo"></a>
    </div>
    <div id="main-content" class="{{ self._TemplateReference__context.name.split('.html')[0] }}">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <ul>
            {% for message in messages %}
            <li>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        {% endwith %}
        {% block content %}{% endblock %}
    </div>
    <div id="footer">
        Spotify Playlist Lookup is independent of Spotify AB, but we do use the Spotify API<br>
        © Dāgs Ādams Grīnbergs 2022
    </div>
</body>

</html>

services/web/app/templates/import_playlists.html
{% extends "base.html" %}

{% block content %}

<h2>Import Playlists</h2>

<form action="" method="post" novalidate>
    {{ form.hidden_tag() }}
    <p>
        {{ form.playlist_ids }}<br>
    </p>
    <p>{{ form.submit() }}</p>
</form>

{% endblock %}

services/web/app/templates/index.html
{% extends "base.html" %}


{% block content %}
<strong id="inline-logo">Spotify Playlist Lookup</strong> is an open-source service for music discovery.

<div id="homepage-stats">
    Currently we keep track of <b>{{ playlist_count }}</b> Spotify playlists and <b>{{ track_count }}</b> tracks
</div>

<a id="spotify-login-button" href="{{ url_for('route_blueprint.search_playlists') }}">Search Playlists</a>
{% endblock %}

services/web/app/templates/login.html
{% extends "base.html" %}

{% block content %}
<h1>Sign In</h1>
<form action="" method="post" novalidate>
    {{ form.hidden_tag() }}
    <p>
        {{ form.username.label }}<br>
        {{ form.username(size=32) }}
        {% for error in form.username.errors %}
        <span>[{{ error }}]</span>
        {% endfor %}
    </p>
    <p>
        {{ form.password.label }}<br>
        {{ form.password(size=32) }}
        {% for error in form.password.errors %}
        <span>[{{ error }}]</span>
        {% endfor %}
    </p>
    <p>{{ form.remember_me() }} {{ form.remember_me.label }}</p>
    <p>{{ form.submit() }}</p>
</form>
<p>New User? <a href="{{ url_for('route_blueprint.register') }}">Click to Register!</a></p>
{% endblock %}

services/web/app/templates/register.html
{% extends 'base.html' %}

{% block content %}
<h1>Register</h1>
<form action="" method="POST">
    {{ form.hidden_tag() }}
    <p>
        {{ form.username.label }}<br>
        {{ form.username(size=32) }}<br>
        {% for error in form.username.errors %}
        <span>[{{ error }}]</span>
        {% endfor %}
    </p>
    <p>
        {{ form.email.label }}<br>
        {{ form.email(size=64) }}<br>
        {% for error in form.email.errors %}
        <span>[{{ error }}]</span>
        {% endfor %}
    </p>
    <p>
        {{ form.password.label }}<br>
        {{ form.password(size=32) }}<br>
        {% for error in form.password.errors %}
        <span>[{{ error }}]</span>
        {% endfor %}
    </p>
    <p>
        {{ form.password2.label }}<br>
        {{ form.password2(size=32) }}<br>
        {% for error in form.password2.errors %}
        <span>[{{ error }}]</span>
        {% endfor %}
    </p>
    <p>{{ form.submit() }}</p>
</form>
{% endblock content %}

services/web/app/templates/search_playlists.html
{% extends "base.html" %}

{% block content %}

<h2>Search Playlists</h2>

<!-- <p>
        So you have a song.It perfectly fits what you want to listen to right now.<br />
        You want more like it, but can't quite explain what exactly it is that you want.<br />
    </p> -->

<form action="" method="post" novalidate>
    {{ form.hidden_tag() }}

    <div id="search-fields">
        {{ form.track_name.label }} {{ form.track_name }}
        {{ form.track_link.label }} {{ form.track_link }}
    </div>

    {{ form.submit() }}

    <div id="search-output">
        {% if results is iterable and (results is not string and results is not mapping) %}
        {% for p in results %}
        <a href="https://open.spotify.com/playlist/{{p.spotify_id}}" target="blank">
            <div class="found-playlist-card">
                <img src="{{ p.image_url }}" alt="image for {{ p.name }}" loading="lazy">
                <div>
                    <h2 class="playlist-name">{{ p.name }}</h2>
                    <span class="playlist-owner">{{ p.owner_name }}</span>
                    <div class="playlist-description">{{ p.description }}</div>
                </div>
                <img class="spotify-logo"
                    src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Spotify_logo_without_text.svg/2048px-Spotify_logo_without_text.svg.png"
                    alt="spotify logo">
            </div>
        </a>

        {# <iframe style="border-radius:12px" src="https://open.spotify.com/embed/playlist/{{ r }}?utm_source=generator"
            width="100%" height="380" frameBorder="0" allowfullscreen=""
            allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"></iframe> #}
        {% endfor %}
        {% else %}
        {{ results }}
        {% endif %}
    </div>
</form>

{% endblock %}